version: '2'
services:
  moodle:
    image: docker.io/bitnami/moodle:3
    ports:
      - '9091:8080'
    environment:
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=postgres14cont
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_USER=postgres
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=mysecretpassword29
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
networks:
  default:
    external:
      name: moodle_mnetwork
volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
